development:
  adapter: mysql
  database: library_development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  database: library_test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql
  database: library_production
  username: root
  password: root
  host: localhost

